apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: jenkins
spec:
  serviceAccountName: workload-service-account
  automountServiceAccountToken: false
  containers:
    - name: test-pod
      image: google/cloud-sdk:slim
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
          ephemeral-storage: 10Mi
