apiVersion: v1
kind: Pod
metadata:
  name: utility
  labels:
    name: utility
spec:
  containers:
    - name: utility
      image: sekharinweb/utility:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
