apiVersion: v1
kind: Pod
spec:
  serviceAccountName: terraform-service-account
  automountServiceAccountToken: false
  containers:
    - name: dotnetcore
      image: mcr.microsoft.com/dotnet/sdk:6.0
      command:
        - sleep
      args:
        - 99d
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - sleep
      args:
        - 9999999
  restartPolicy: Never
