apiVersion: v1
kind: Pod
metadata:
  name: terraform
  labels:
    name: terraform
spec:
  serviceAccountName: terraform-service-account
  automountServiceAccountToken: false
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
    - name: terraform
      image: hashicorp/terraform
      command: ["/bin/sh", "-c"]
      args:
        - cat
      tty: true
    - name: curl
      image: curlimages/curl
      command: ["sh", "-c", "while true; do sleep 3600; done"]
