apiVersion: v1
kind: Pod
metadata:
  name: "multicontainerpod"
  namespace: default
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
    - name: busybox-container
      image: busybox:latest
      args:
        - sleep
        - "3600"
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
